#
CPP = g++
CFLAG = -c
OFLAG = -o

OBJ = test.o handle.o
TARGET = test

#.SUFFIXES: .cpp .o
#.cpp.o:
#	$(CPP) $(CFLAG) $<
all:$(OBJ)
	$(CPP) $(OFLAG) $(TARGET) $(OBJ)

test.o:test.cpp handle.o
	$(CPP) $(CFLAG) test.cpp

handle.o:handle.cpp
	$(CPP) $(CFLAG) handle.cpp

clean:
	rm -rf test
	rm -rf *.o
